# Generated by Django 3.0.3 on 2020-03-18 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('main', '0001_initial'), ('main', '0002_auto_20200304_1916'), ('main', '0003_auto_20200305_0003'), ('main', '0004_auto_20200305_0223'), ('main', '0005_remove_bug_status'), ('main', '0006_category'), ('main', '0007_delete_category'), ('main', '0008_bug_x'), ('main', '0009_auto_20200312_2227'), ('main', '0010_delete_counter'), ('main', '0011_bug_page'), ('main', '0012_remove_bug_page'), ('main', '0013_bug_paged'), ('main', '0014_remove_bug_paged'), ('main', '0015_bug_block'), ('main', '0016_remove_bug_block'), ('main', '0017_bug_paging'), ('main', '0018_bug_paged'), ('main', '0019_prop'), ('main', '0020_auto_20200316_1538'), ('main', '0021_bug_paged'), ('main', '0022_auto_20200316_1627'), ('main', '0023_delete_paging'), ('main', '0024_auto_20200317_2218'), ('main', '0025_auto_20200317_2227'), ('main', '0026_auto_20200317_2239'), ('main', '0027_auto_20200317_2256')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('complete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('fname', models.CharField(blank=True, default='', max_length=200)),
                ('lname', models.CharField(blank=True, default='', max_length=200)),
                ('summary', models.TextField(null=True)),
                ('component', models.CharField(default='', max_length=200)),
                ('version', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
        ),
    ]
